Gh xtcu ble module teq fw
auralix/alx-202-af-10-1-auralix-c-lib pull request #10
Opened 2023-01-11 16:34 UTC by gregorhudin

2023-01-11 20:22 UTC, tomazvidovic requested changes
In general stuff is OK
We must update whole library to new systems, so that all examples are OK...

TODO improve DeInit function

TODO Also when writing WEAK function, use enums always, so you don't need comments..

````
void AlxVeml6040_RegStruct_SetVal(AlxVeml6040* me)
{
	me->reg._0x00_CONF		.val.SD = 0; // enable sensor
	me->reg._0x00_CONF		.val.AF = 0; // Auto mode enabled
	me->reg._0x00_CONF		.val.TRIG = 0; // trigger disabled (if you want use Trigger - set AF = 1)
	me->reg._0x00_CONF		.val.IT = 0b000; // 40ms -> refreshing time for new data
}
````

Like this:

````
void AlxPca9431_RegStruct_SetVal(AlxPca9431* me)
{
	// ADC enable
	me->reg._0Dh_ADC_CONTROL.val.ADC_EN = AdcEn_Enabled;
	me->reg._0Dh_ADC_CONTROL.val.ADC_AVG_EN = AdcAveragingEn_Enabled;
	me->reg._0Dh_ADC_CONTROL.val.ADC_RATE = AdcRate_1ShotConversion;
	me->reg._21h_VOUTLDO_OCP.val.VOUTLDO_OCP = VOutLdoSetOCP_70mA;	// 0x08->40mA, 0x0E->70mA, 0x12->90mA, 0x1C->140mA

	// ADC sample enable
	me->reg._0Eh_Sample_EN.val.NTC_ADC_EN   = NtcAdcSamplingEn_Disabled;
	me->reg._0Eh_Sample_EN.val.OTP_ADC_EN   = OtpAdcSamplingEn_Disabled;
	me->reg._0Eh_Sample_EN.val.IOUT_ADC_EN  = IOutAdcSamplingEn_Enabled;
	me->reg._0Eh_Sample_EN.val.VOUT_ADC_EN  = VOutAdcSamplingEn_Disabled;
	me->reg._0Eh_Sample_EN.val.IRECT_ADC_EN = IRectAdcSamplingEn_Disabled;
	me->reg._0Eh_Sample_EN.val.VRECT_ADC_EN = VRectAdcSamplingEn_Enabled;
	me->reg._0Eh_Sample_EN.val.VTUNE_ADC_EN = VTuneAdcSamplingEn_Disabled;
}
````


Connected to 
auralix/alx-202-af-23-auralix-c-cpp-lib-wiki#39

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.h
> -		uint8_t unused_3 : 1;  // bit 3 is unused
Old system, I think we do not need this comment, it is clear enough from variable name..

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.h
> -//******************************************************************************
It is better to just delete all empty sections

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.h
> -	// Objects - External
Old system, currently we just have:
- Const
- Parameters
- Variables
- Info

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.c
> -	// Prepare variables
Old system, we will now use always "Local variables"

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.c
> -	if (status != Alx_Ok) { ALX_VEML6040_TRACE("Err_AlxI2c_Init"); return status; }
Old system, here is OK, to just write "Err" everywhere for TRACE, if error happens, filename, function name & line number will be traced via UART, you can quickly find by this where this happened

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.c
> -	status = AlxI2c_Master_IsSlaveReady(me->i2c, me->i2cAddr, 3, 1000);
here it should be me->i2cNumOfTries, me->i2cTimeout_ms ...

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.c
> +	// Return
new system, we will just use Return it is more clear

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.c
> +	// Read
Here I found out that comments that indicate code steps its is better that they are short..
So here I just Read

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.c
> +	// Set
Also short comment just Set

2023-01-11 20:22 UTC, tomazvidovic commented on Ext/alxVeml6040.c
> +	// TV: TODO Disable IC, so that is stops sampling light sensor
TODO, here you must disable IC, then DeInit is correct..

2023-01-12 11:13 UTC, gregorhudin commented on Ext/alxVeml6040.c
> +	// TV: TODO Disable IC, so that is stops sampling light sensor
// Veml6040 Set To Default - Disabled IC, so that is stops sampling light sensor
	AlxVeml6040_RegStruct_SetToDefault(me);

2023-01-12 11:32 UTC, gregorhudin commented
me->reg._0x00_CONF		.val.SD		= ColorSensor_Enabled;
	me->reg._0x00_CONF		.val.AF		= AutoMode;
	me->reg._0x00_CONF		.val.TRIG	        = TriggerDisabled;
	me->reg._0x00_CONF		.val.IT		= IntegrationTimeSelect_40_ms;

2023-01-12 11:41 UTC, tomazvidovic commented on Ext/alxVeml6040.c
> +	AlxVeml6040_RegStruct_SetToDefault(me);
You forgot to call regWrite to set actual IC..

2023-01-12 12:23 UTC, gregorhudin commented on Ext/alxVeml6040.c
> +	AlxVeml6040_RegStruct_SetToDefault(me);
// Set register struct values to default
	AlxVeml6040_RegStruct_SetToDefault(me);

	// Write registers - Disabled IC
	status = AlxVeml6040_Reg_Write_All(me);
	if (status != Alx_Ok) { ALX_VEML6040_TRACE("Err"); return status; }

2023-01-12 16:07 UTC, tomazvidovic approved these changes

2023-01-12 16:13 UTC, merged